### ISSUE TITLE
Issue with bluetooth

### ISSUE THREAD

**Issue by im6h** [sunabozu/Dell_E5470_OpenCore#1]
Thanks for your contribute, I used your EFI folder in my machine.
My hardware:
- Name: Dell E5470
- CPU: Intel core I7 - 6820HQ
- RAM: 16GB - 2133MHz
- GPU: Intel graphic 530
- OS: Bigsure 11.6.1

Your EFI is cool bootloader :D. Can you fix issue with bluetooth?
One time, thanks for contribute.

**Comment by sunabozu** [comment]
Bluetooth works for me. Check your hardware Airplane mode, it may be activated.
